#!/usr/bin/env python3
"""Compute the bench references with scipy and keep only the digits independent solvers agree on.

Policy: a reference comes from independent solvers at tolerances far tighter than the
table needs, and only the digits on which all of them agree are stored. The solvers are scipy's Radau (rtol 1e-13),
BDF and LSODA (rtol 1e-12), all with atol 1e-20 and finite-difference Jacobians. A solver that fails is recorded and
left out; fewer than two that succeed is an error, and so is an agreement below MIN_DIGITS.

    python3 references.py            recompute, then rewrite bench/reference.ml and references.json
    python3 references.py --check    recompute and verify both files; write nothing

--check holds three things: reference.ml is what references.json generates, the stored digits are what the raw solver
values in references.json give, and a fresh run still gives those raw values to within how far apart the solvers were
(the stored digits sit at the edge of that disagreement, so a platform's last bits must not fail the check).

vstiff never computes a reference: it could not catch its own mistakes with one.
"""

import argparse
import json
import platform
import sys
from pathlib import Path

import numpy as np
import scipy
from scipy.integrate import solve_ivp

from problems import PROBLEMS

ROOT = Path(__file__).resolve().parents[2]
JSON_PATH = ROOT / "bench" / "compare" / "references.json"
OCAML_PATH = ROOT / "bench" / "reference.ml"

SOLVERS = (("Radau", 1e-13), ("BDF", 1e-12), ("LSODA", 1e-12))
ATOL = 1e-20
MIN_DIGITS = 8  # fewer could not judge a run at rtol 1e-8
MAX_DIGITS = 15

DESCRIPTIONS = {
    "robertson": "Robertson from y(0) = (1, 0, 0)",
    "hires": "HIRES from y(0) = (1, 0, 0, 0, 0, 0, 0, 0.0057)",
    "van_der_pol": "van der Pol, mu = 1000, from y(0) = (2, 0)",
    "brusselator_80": "The Brusselator on 40 cells (n = 80), alpha = 1/50, from u = 1 + sin(2 pi x_i), v = 3",
}


def run_solver(problem, method, rtol):
    sol = solve_ivp(problem.rhs, (0.0, problem.t_end), problem.y0, method=method, rtol=rtol, atol=ATOL)
    run = {
        "method": method,
        "rtol": rtol,
        "success": bool(sol.success),
        "status": int(sol.status),
        "steps": len(sol.t) - 1,
        "nfev": int(sol.nfev),
    }
    if sol.success:
        run["y"] = [float(v) for v in sol.y[:, -1]]
    else:
        run["message"] = sol.message
    return run


def agreed(values):
    """The largest k <= MAX_DIGITS for which all values round to one k-digit decimal, and that decimal; (0, None) if
    there is none."""
    for k in range(MAX_DIGITS, 0, -1):
        rounded = {float(f"{v:.{k - 1}e}") for v in values}
        if len(rounded) == 1:
            return k, rounded.pop()
    return 0, None


def store(runs):
    """Per component: the stored value, how many digits agree and the largest difference between the solvers."""
    good = [r for r in runs if r["success"]]
    if len(good) < 2:
        sys.exit("fewer than two solvers succeeded: " + ", ".join(f"{r['method']} {r['success']}" for r in runs))
    stored = {"y": [], "digits": [], "spread": []}
    for i in range(len(good[0]["y"])):
        values = [r["y"][i] for r in good]
        digits, value = agreed(values)
        if digits < MIN_DIGITS:
            sys.exit(f"y{i + 1}: the solvers agree to {digits} digits, fewer than {MIN_DIGITS}: {values}")
        stored["y"].append(value)
        stored["digits"].append(digits)
        stored["spread"].append(max(values) - min(values))
    return stored


def compute():
    versions = {
        "python": platform.python_version(),
        "numpy": np.__version__,
        "scipy": scipy.__version__,
        "machine": platform.machine(),
    }
    document = {"versions": versions, "atol": ATOL, "problems": {}}
    for name, problem in PROBLEMS.items():
        runs = [run_solver(problem, method, rtol) for method, rtol in SOLVERS]
        document["problems"][name] = {"t_end": problem.t_end, "runs": runs, "stored": store(runs)}
    return document


def tolerance(run):
    return f"{run['method']} rtol {run['rtol']:g}"


def ocaml_source(document):
    v = document["versions"]
    out = [
        "(* Generated by bench/compare/references.py from bench/compare/references.json: run the script, do not edit",
        "   by hand. Each value keeps the digits on which all the solvers that succeeded agree. *)",
        "",
        "type t = { t_end : float; y : float array }",
    ]
    for name, entry in document["problems"].items():
        good = [r for r in entry["runs"] if r["success"]]
        bad = [r for r in entry["runs"] if not r["success"]]
        out += [
            "",
            f"(* {DESCRIPTIONS[name]}, at t = {entry['t_end']:.15g}.",
            f"   scipy {v['scipy']} solve_ivp (numpy {v['numpy']}, Python {v['python']}, {v['machine']}),"
            f" atol {document['atol']:g},",
            f"   finite-difference Jacobians: {', '.join(tolerance(r) for r in good)}.",
        ]
        if bad:
            failed = ", ".join(f"{tolerance(r)} (status {r['status']})" for r in bad)
            out.append(f"   Left out, the run failed: {failed}.")
        out.append("   After each value: how many digits agree, and the largest difference between the solvers. *)")
        stored = entry["stored"]
        out += [f"let {name} =", "  {", f"    t_end = {entry['t_end']!r};", "    y =", "      [|"]
        for i, (value, digits, spread) in enumerate(zip(stored["y"], stored["digits"], stored["spread"])):
            out.append(f"        {value!r} (* y{i + 1}: {digits} digits, spread {spread:.1e} *);")
        out += ["      |];", "  }"]
    return "\n".join(out) + "\n"


def check(fresh, stored_document, stored_ocaml):
    """What is wrong with the stored files, judged against a fresh computation (nothing, when they hold)."""
    problems = []
    if ocaml_source(stored_document) != stored_ocaml:
        problems.append(f"{OCAML_PATH.name} is not what {JSON_PATH.name} generates")
    for name, entry in stored_document["problems"].items():
        if store(entry["runs"]) != entry["stored"]:
            problems.append(f"{name}: the stored digits are not what the raw solver values in {JSON_PATH.name} give")
    for name, entry in fresh["problems"].items():
        stored_entry = stored_document["problems"][name]
        good = [r for r in entry["runs"] if r["success"]]
        stored_good = [r for r in stored_entry["runs"] if r["success"]]
        if [r["method"] for r in good] != [r["method"] for r in stored_good]:
            problems.append(f"{name}: the solvers that succeed are not those of {JSON_PATH.name}")
            continue
        spreads = stored_entry["stored"]["spread"]
        for run, stored_run in zip(good, stored_good):
            if len(run["y"]) != len(stored_run["y"]):
                problems.append(f"{name}: {tolerance(run)} gives {len(run['y'])} components, not {len(spreads)}")
                continue
            for i, spread in enumerate(spreads):
                moved = abs(run["y"][i] - stored_run["y"][i])
                if moved > spread:
                    problems.append(f"{name} y{i + 1}: {tolerance(run)} moved by {moved:.1e}, over {spread:.1e}")
    return problems


def report(document):
    for name, entry in document["problems"].items():
        print(f"{name} at t = {entry['t_end']:.15g}")
        for r in entry["runs"]:
            outcome = f"{r['steps']} steps, {r['nfev']} rhs calls" if r["success"] else f"FAILED, status {r['status']}"
            print(f"  {r['method']:6s} rtol {r['rtol']:g}: {outcome}")
        stored = entry["stored"]
        digits = f"{min(stored['digits'])} to {max(stored['digits'])}"
        print(f"  stored: {digits} digits, spread up to {max(stored['spread']):.1e}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify the stored files against a fresh computation")
    args = parser.parse_args()
    document = compute()
    report(document)
    if args.check:
        problems = check(document, json.loads(JSON_PATH.read_text()), OCAML_PATH.read_text())
        for problem in problems:
            print("MISMATCH:", problem)
        print("the stored references hold" if not problems else f"{len(problems)} mismatches")
        return 1 if problems else 0
    JSON_PATH.write_text(json.dumps(document, indent=2, allow_nan=False) + "\n")
    OCAML_PATH.write_text(ocaml_source(document))
    print(f"wrote {JSON_PATH.relative_to(ROOT)} and {OCAML_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
